on:
  push:
    branches: [ main, ci* ]
    tags: [ pre*, v* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build with wasm-pack
        run: cargo install wasm-pack && wasm-pack build
      - name: List files
        run: ls -la